### ISSUE TITLE
How do I load the pretrained model to test word sense disambiguation on a sentence?

### ISSUE THREAD

**Issue by TheoSeo93** [nusnlp/esr#1]
Hi ! I've read the paper and it seems very impressive to me. 
I wanted to run wsd over some raw texts from pretrained model, but I'm quite frustrated at figuring out how to load the model. How can I load the model to perform a word sense disambiguation on a simple sentence?

**Comment by sonodasong** [comment]
We have updated the folder structure of the zip file containing trained models.
The link for the new zip file is updated in [README.md](https://github.com/nusnlp/esr/blob/main/README.md#using-trained-models).
Please follow the fold structure according to the zip file to place the trained models.

The code now only supports testing on the evaluation datasets.
If you want to test your own sentence, you can follow the format of the evaluation datasets and create one for the sentence.

**Comment by TheoSeo93** [comment]
From my understanding, once I place the model to the corresponding folder structure and run the sh script, it will perform the evaluation on the datasets.  

Thank you!

**Comment by sonodasong** [comment]
> From my understanding, once I place the model to the corresponding folder structure and run the sh script, it will perform the evaluation on the datasets.
> 

That's correct. Thanks for feedback.
